export const RENAMES = {
  DOCUMENTOS_IMPORTADOR_EXPORTADOR: {
    DOCUMENTOS_IMPORTADOR: {
      ACTA_CONSTITUTIVA: "ACTA_CONSTITUTIVA",
      PODER_NOTARIAL: "PODER_NOTARIAL",
    },
    DATOS_CONTACTO_DEL_IMPORTADOR: {
      COMPROBANTE_DE_DOMICILIO: "COMPROBANTE_DE_DOMICILIO",
      FOTOS_DOMICILIO_FISCAL: "FOTOS_DOMICILIO_FISCAL",
      FOTOS_ACREDITACION_LEGAL_INMUEBLE: "FOTOS_ACREDITACION_LEGAL_INMUEBLE",
      FOTOS_LUGAR_ACTIVIDADES: "FOTOS_LUGAR_ACTIVIDADES",
    },
    DATOS_HACIENDA_IMPORTADOR: {
      CERTIFICADO_SAT: "CERTIFICADO_SAT",
      EFIRMA_SAT: "EFIRMA_SAT",
      CONSTANCIA_SITUACION_FISCAL_SAT: "CONSTANCIA_SITUACION_FISCAL_SAT",
    },
  },
};
