export type StatusOptions = Record<string, string[]>;

export const statusOptions: StatusOptions = {
  Cliente: [
    "Clasificación requiere más información y estamos en espera de información del cliente",
    "Cliente con adeudo, no se libera embarque",
    "Cliente tiene cambio de domicilio",
    "Embarque con plaga",
    "En espera de anticipo del cliente",
    "En espera de instrucciones del cliente",
    "En proceso de desconsolidación",
    "Hay discrepancias entre el previo y la documentación, se esta en revisión con el cliente",
    "Mercancía en abandono, se va a dejar por instrucción del cliente",
    "Mercancía en abandono, se va a liberar",
    "Mercancía pendiente de arribo",
    "Mercancía requiere RRNA y no se cuenta con el documento por parte del cliente",
    "Operación cancelada",
    "Pre alerta sin documentos",
    "Proforma enviada al cliente, en espera de vo.bo.",
    "Requiere carta cupo/en espera de carta cupo",
    "Roll de buque por Cliente",
    "Se requiere carta poder para revalidación",
    "Se solicito al cliente documentos comerciales correctos",
    "Se solicito información adicional del cliente para captura de pedimento",
  ],
  AAP: [
    "Cliente compartió información técnica para clasificar",
    "Ejecutivo realizando cambios de glosa",
    "En espera del previo",
    "En proceso de captura de pedimento",
    "En proceso de validación y pago de pedimento",
    "En proceso maniobra de vacío",
    "En revisión de glosa",
    "En revisión del previo por parte del ejecutivo",
    "Mercancía clasificada",
    "Pedimento pagado con cita de despacho programada",
    "Pedimento pagado, en espera de cita de despacho",
    "Pre alerta con documentos, en proceso de captura de factura",
    "Requiere inspección PROFEPA/SAGARPA",
    "Se solicito clasificación arancelaria",
  ],
  Autoridad: [
    "Carga retenida en puntos tácticos",
    "Roll de buque por puntos tácticos",
  ],
  Concluido: ["Mercancía liberada de aduana", "Pedimento modulado"],
};
