export const PERM = {
  ADMIN_USUARIOS: "ADMIN_USUARIOS",
  ADMIN_ACCESOS: "ADMIN_ACCESOS",

  DASHBOARD_TRAFICO: "DASHBOARD_TRAFICO",
  DASHBOARD_TRAFICO_ADMIN: "DASHBOARD_TRAFICO_ADMIN",

  DEA_DESCARGAR_ARCHIVOS: "DEA_DESCARGAR_ARCHIVOS",
  DEA_EXP_DIGITAL: "DEA_EXP_DIGITAL",
  DEA_PREVIOS: "DEA_PREVIOS",
  DEA_SUBIR_ARCHIVOS: "DEA_SUBIR_ARCHIVOS",

  OPERACIONES_MODIFICAR_REFERENCIAS: "OPERACIONES_MODIFICAR_REFERENCIAS",

  SISTEMAGIP_EXPLORADOR: "SISTEMAGIP_EXPLORADOR",

  TRANSBEL_ENTREGAS: "TRANSBEL_ENTREGAS",
  TRANSBEL_INTERFAZ: "TRANSBEL_INTERFAZ",
  TRANSBEL_CARGUES: "TRANSBEL_CARGUES",
  TRANSBEL_CARGUE_MANUAL: "TRANSBEL_CARGUE_MANUAL",
  TRANSBEL_DATOS_EMBARQUE: "TRANSBEL_DATOS_EMBARQUE",
} as const;

export type Permission = (typeof PERM)[keyof typeof PERM];
