export const clientsData = [
  {
    CVE_IMP: "000259",
    NOM_IMP: "TRANSBEL SA DE CV",
  },
  {
    CVE_IMP: "004563",
    NOM_IMP: "ELEVADORES OTIS S DE RL DE CV",
  },
  {
    CVE_IMP: "004681",
    NOM_IMP: "CERRADURAS Y CANDADOS PHILLIPS SA DE CV",
  },
  {
    CVE_IMP: "001152",
    NOM_IMP: "LUXOTTICA MEXICO S.A DE C.V",
  },
  {
    CVE_IMP: "IMPORT",
    NOM_IMP: "SISTEMAS Y SERVICIOS DE COMUNICACION S.A. DE C.V.",
  },
  {
    CVE_IMP: "000041",
    NOM_IMP: "RICOH MEXICANA SA DE CV",
  },
  {
    CVE_IMP: "001080",
    NOM_IMP: "ALFA LAVAL SA DE CV",
  },
  {
    CVE_IMP: "00439C",
    NOM_IMP: "HELVEX SA DE CV",
  },
  {
    CVE_IMP: "000588",
    NOM_IMP: "PELIKAN MEXICO S.A DE C.V",
  },
  {
    CVE_IMP: "000456",
    NOM_IMP: "KIRIU MEXICANA SA DE CV ",
  },
  {
    CVE_IMP: "004000",
    NOM_IMP: "HANSGROHE S DE R.L DE C.V",
  },
  {
    CVE_IMP: "004523",
    NOM_IMP: "ODW-ELEKTRIK MEXICO S DE RL DE CV",
  },
  {
    CVE_IMP: "004010",
    NOM_IMP: "MULTIBOLSAS PLASTICAS SA DE CV ",
  },
  {
    CVE_IMP: "004755",
    NOM_IMP: "ESSILOR MEXICO SA DE CV",
  },
  {
    CVE_IMP: "004002",
    NOM_IMP: "HASCO NORMALIEN MEXICO SA DE CV",
  },
  {
    CVE_IMP: "004713",
    NOM_IMP: "RC KAIROS SA DE CV",
  },
  {
    CVE_IMP: "004025",
    NOM_IMP: "ABAMEX INGENIERIA SA DE CV",
  },
  {
    CVE_IMP: "00401M",
    NOM_IMP: "UNIVERSIDAD NACIONAL AUTONOMA DE MEXICO",
  },
  {
    CVE_IMP: "001065",
    NOM_IMP: "SAFILO DE MEXICO SA DE CV",
  },
  {
    CVE_IMP: "004051",
    NOM_IMP: "HOTELHAUS SA DE CV",
  },
  {
    CVE_IMP: "004304",
    NOM_IMP: "MINI GRIP DE MEXICO SA DE CV",
  },
  {
    CVE_IMP: "004797",
    NOM_IMP: "PRO KIO LOGISTICS S DE RL DE CV",
  },
  {
    CVE_IMP: "001239",
    NOM_IMP: "MOENDI DISTRIBUCION SAPI DE C.V. ",
  },
  {
    CVE_IMP: "000848",
    NOM_IMP: "PING SOLUTIONS S DE RL DE  CV",
  },
  {
    CVE_IMP: "004634",
    NOM_IMP: "PAMPA MUEBLES DE MADERA SA DE CV",
  },
  {
    CVE_IMP: "004832",
    NOM_IMP: "ELECTRONICA Y MEDICINA S.A.",
  },
  {
    CVE_IMP: "004096",
    NOM_IMP: "FRILCO PROMOCIONES SA DE CV",
  },
  {
    CVE_IMP: "00401J",
    NOM_IMP: "UNIVERSIDAD NACIONAL AUTONOMA DE MEXICO",
  },
  {
    CVE_IMP: "004752",
    NOM_IMP: "NOVEM CLOUD MEXICO S DE RL DE CV",
  },
  {
    CVE_IMP: "001267",
    NOM_IMP: "KONE MEXICO SA DE CV ",
  },
  {
    CVE_IMP: "004445",
    NOM_IMP: "HUBBELL PRODUCTS MEXICO S DE RL DE CV",
  },
  {
    CVE_IMP: "004423",
    NOM_IMP: "COMPLACAN S. DE R.L. DE C.V.",
  },
  {
    CVE_IMP: "004323",
    NOM_IMP: "DISE�O Y METALMECANICA SA DE CV",
  },
  {
    CVE_IMP: "004498",
    NOM_IMP: "MARCOLIN MEXICO SAPI DE CV",
  },
  {
    CVE_IMP: "004820",
    NOM_IMP: "BUNZL DE MEXICO S DE RL DE CV",
  },
  {
    CVE_IMP: "004551",
    NOM_IMP: "QUIMICA CARIBE LTDA S DE RL DE CV",
  },
  {
    CVE_IMP: "004705",
    NOM_IMP: "IMPORTACIONES BERSAL SA DE CV",
  },
  {
    CVE_IMP: "004798",
    NOM_IMP: "ANDRITZ FABRICS AND ROLLS SA DE CV",
  },
  {
    CVE_IMP: "004616",
    NOM_IMP: "COMERCIALIZADORA TOTAL TRADE SA DE CV",
  },
  {
    CVE_IMP: "004671",
    NOM_IMP: "UNIXEL SA DE CV",
  },
  {
    CVE_IMP: "004054",
    NOM_IMP: "MEXICANA DE DRAGADOS S.A DE C.V",
  },
  {
    CVE_IMP: "004016",
    NOM_IMP: "CORPORACION ANALITICA INTEGRAL SA DE CV",
  },
  {
    CVE_IMP: "004354",
    NOM_IMP: "TANGERINE DISTRIBUTIONS S.A. DE C.V.",
  },
  {
    CVE_IMP: "004038",
    NOM_IMP: "INTERBIOL SA  DE CV",
  },
  {
    CVE_IMP: "004067",
    NOM_IMP: "PLASTICOS ITALIANOS SA DE CV",
  },
  {
    CVE_IMP: "004077",
    NOM_IMP:
      "FABRICANTE IMPORTADOR  SUMINISTRADOR EXPORTADOR  INDUSTRIAL SA DE CV",
  },
  {
    CVE_IMP: "004003",
    NOM_IMP: "IMPORTACIONES EXCLUSIVAS POLANCO SA DE CV",
  },
  {
    CVE_IMP: "004850",
    NOM_IMP: "CFS BRANDS DISPENSING SA DE CV",
  },
  {
    CVE_IMP: "004028",
    NOM_IMP: "INSCO DE MEXICO SA DE CV / AMPHENOL THERMOMETRICS INC",
  },
  {
    CVE_IMP: "004928",
    NOM_IMP: "FAST INT L INVESTMENT LIMITED SA DE CV",
  },
  {
    CVE_IMP: "004042",
    NOM_IMP: "STRATASCAN MEXICO S.A DE C.V.",
  },
  {
    CVE_IMP: "004630",
    NOM_IMP: "EISSMANN AUTOMOTIVE DE MEXICO SA DE CV",
  },
  {
    CVE_IMP: "004846",
    NOM_IMP: "YANMEX SA DE CV",
  },
  {
    CVE_IMP: "004420",
    NOM_IMP: "SANIVEX SA DE CV",
  },
  {
    CVE_IMP: "004817",
    NOM_IMP: "INTEGRACION DE SOLUCIONES MAC&C S DE RL DE CV",
  },
  {
    CVE_IMP: "004001",
    NOM_IMP: "JOYMATIC SA DE CV ",
  },
  {
    CVE_IMP: "004086",
    NOM_IMP: "MAKRO BUSINESS S.A DE C.V ",
  },
  {
    CVE_IMP: "004057",
    NOM_IMP: "WILD FLAVORS SA DE CV",
  },
  {
    CVE_IMP: "004408",
    NOM_IMP: "COMERCIALIZADORA OFFSHORE SA DE CV",
  },
  {
    CVE_IMP: "004494",
    NOM_IMP: "PROYECTOS XOLOTL SA DE CV",
  },
  {
    CVE_IMP: "004628",
    NOM_IMP: "IRV SOLUCIONES SA DE CV",
  },
  {
    CVE_IMP: "004348",
    NOM_IMP: "VEOLUS ENERGIA Y GESTION TECNICA S.A. DE C.V.",
  },
  {
    CVE_IMP: "004049",
    NOM_IMP: "CASKA MEXICO S.A DE C.V ",
  },
  {
    CVE_IMP: "004062",
    NOM_IMP: "BOLEX SA DE CV",
  },
  {
    CVE_IMP: "004015",
    NOM_IMP: "DE LORENZO OF AMERICA CORP S.A DE C.V",
  },
  {
    CVE_IMP: "00401P",
    NOM_IMP: "UNIVERSIDAD NACIONAL AUTONOMA DE MEXICO",
  },
  {
    CVE_IMP: "004262",
    NOM_IMP: "INDUSTRIAS LET SA DE CV",
  },
  {
    CVE_IMP: "0040MM",
    NOM_IMP: "UNIVERSIDAD NACIONAL AUTONOMA DE MEXICO",
  },
  {
    CVE_IMP: "004095",
    NOM_IMP: "GLOBAL TECHNICAL SOLUTIONS DE MEXICO SA DE CV",
  },
  {
    CVE_IMP: "004269",
    NOM_IMP: "UNIXEL DIVISION INDUSTRIAL SA DE CV",
  },
  {
    CVE_IMP: "004791",
    NOM_IMP: "SINOPEC INTERNATIONAL PETROLEUM SERVICE MEXICO S DE RL DE CV",
  },
  {
    CVE_IMP: "004930",
    NOM_IMP: "PREMIER TECH SISTEMAS Y AUTOMATIZACION SA DE CV",
  },
  {
    CVE_IMP: "004452",
    NOM_IMP: "INDUSTRIAS DE LINAMAR SA DE CV",
  },
  {
    CVE_IMP: "004542",
    NOM_IMP: "CODELVEX S.A DE C.V",
  },
  {
    CVE_IMP: "004600",
    NOM_IMP: "NATURACEITES S.A",
  },
  {
    CVE_IMP: "004800",
    NOM_IMP: "EDICIONES LAROUSSE SA DE CV",
  },
  {
    CVE_IMP: "004460",
    NOM_IMP: "TOSHIBA GLOBAL COMMERCE SOLUTIONS MEXICO S DE RL DE CV",
  },
  {
    CVE_IMP: "004801",
    NOM_IMP: "DIFUSORA LAROUSSE MEXICO SA DE CV",
  },
  {
    CVE_IMP: "004099",
    NOM_IMP: "CORPORACION COMEXA S.A DE C.V",
  },
  {
    CVE_IMP: "004377",
    NOM_IMP: "DIAGNOSTIC CHEMICALS LIMITED DE MEXICO SA DE CV",
  },
  {
    CVE_IMP: "004290",
    NOM_IMP: "BLUM MEXICO HERRAJES PARA MUEBLES S DE RL DE CV",
  },
  {
    CVE_IMP: "004080",
    NOM_IMP: "DRILLTEK SA DE CV  ",
  },
  {
    CVE_IMP: "004076",
    NOM_IMP: "PRODUCTOS FLIPPER S.A. DE C.V. ",
  },
  {
    CVE_IMP: "004058",
    NOM_IMP: "SERVICIO INDUSTRIAL PRO ANALISIS SA DE CV",
  },
  {
    CVE_IMP: "004092",
    NOM_IMP: "EL NERVION SA DE CV",
  },
  {
    CVE_IMP: "TEM085",
    NOM_IMP: "PRO KIO LOGISTICS S DE RL DE CV / FREIGHT MINDS USA",
  },
  {
    CVE_IMP: "TEM066",
    NOM_IMP: "PRO KIO LOGISTICS S DE RL DE CV / ROCK IT GLOBAL USA, LLC",
  },
  {
    CVE_IMP: "004873",
    NOM_IMP: "SUMINISTROS M.Q. SA DE CV",
  },
  {
    CVE_IMP: "TEM067",
    NOM_IMP: "PRO KIO LOGISTICS S DE RL DE CV / EFM EVENT LOGISTICS INC",
  },
  {
    CVE_IMP: "004811",
    NOM_IMP: "JABIL CIRCUIT DE CHIHUAHUA S DE RL DE CV",
  },
  {
    CVE_IMP: "TEM071",
    NOM_IMP: "PRO KIO LOGISTICS S DE RL DE CV /  FREIGHT MINDS",
  },
  {
    CVE_IMP: "004783",
    NOM_IMP: "LUXTRANSMEX S DE RL DE CV",
  },
  {
    CVE_IMP: "004848",
    NOM_IMP: "OPERADORA DE CENTROS DE ESPECTACULOS SA DE CV ",
  },
  {
    CVE_IMP: "004014",
    NOM_IMP: "LOGISTICA EXPRESS DE LEON S.A DE C.V",
  },
  {
    CVE_IMP: "004885",
    NOM_IMP: "BELASIA MEXICO SA DE CV",
  },
  {
    CVE_IMP: "004081",
    NOM_IMP: "DIVERSIFIED WELL LOGGING INC",
  },
  {
    CVE_IMP: "004263",
    NOM_IMP: "PROVEEDORA DE RIELES Y DURMIENTES MEXICANOS SA DE CV",
  },
  {
    CVE_IMP: "004536",
    NOM_IMP: "DSI TECNICAS EN PRESFUERZO SA DE CV",
  },
  {
    CVE_IMP: "004607",
    NOM_IMP: "GRUPO ECOTAPAS SA DE CV",
  },
  {
    CVE_IMP: "004218",
    NOM_IMP: "RADIO SURTIDORA S.A DE C.V",
  },
  {
    CVE_IMP: "004865",
    NOM_IMP: "INSUMOS INTERNACIONALES G C SA DE CV",
  },
  {
    CVE_IMP: "TEM073",
    NOM_IMP: "PRO KIO LOGISTICS S DE RL DE CV / PRO KIO LLC ",
  },
  {
    CVE_IMP: "004674",
    NOM_IMP: "NOFIMEX ASOCIADOS SC",
  },
  {
    CVE_IMP: "004617",
    NOM_IMP: "OPERACION Y MANTENIMIENTO DE TELEFERICOS SA DE CV",
  },
  {
    CVE_IMP: "004033",
    NOM_IMP: "LITO OFFSET LEN  SA.  DE CV.",
  },
  {
    CVE_IMP: "004093",
    NOM_IMP: "MIDJA COMERCIALIZADORA S.A DE  C.V ",
  },
  {
    CVE_IMP: "004904",
    NOM_IMP: "ALUMA SYSTEMS MEXICO SA DE CV",
  },
  {
    CVE_IMP: "004670",
    NOM_IMP: "INGENIERIA Y MANTENIMIENTO ELECTRICO INDUSTRIAL SA DE CV",
  },
  {
    CVE_IMP: "004842",
    NOM_IMP: "RAYSCAN MEXICO S DE RL DE CV",
  },
  {
    CVE_IMP: "004308",
    NOM_IMP: "GREEN SOLUTIONS ABAMEX S.A. DE C.V.",
  },
  {
    CVE_IMP: "EXPORT",
    NOM_IMP: "SISTEMAS Y SERVICIOS DE COMUNICACION SA DE CV",
  },
  {
    CVE_IMP: "004412",
    NOM_IMP: "MICRA NANOTECNOLOGIA, SA DE CV",
  },
  {
    CVE_IMP: "004078",
    NOM_IMP: "TRIBOLOGY DE MEXICO  SA  DE CV ",
  },
  {
    CVE_IMP: "004272",
    NOM_IMP: "HERPONS CONTINENTAL SA DE CV",
  },
  {
    CVE_IMP: "004484",
    NOM_IMP: "SERVICIOS SISMICOS DE EXPLORACION",
  },
  {
    CVE_IMP: "004807",
    NOM_IMP: "BEDEMEX SA DE CV",
  },
  {
    CVE_IMP: "004845",
    NOM_IMP: "GARDIEZ EQUIPO HIDRAULICO ALIADO SA DE CV",
  },
  {
    CVE_IMP: "004516",
    NOM_IMP: "FEMI LOGISTICA SA DE CV",
  },
  {
    CVE_IMP: "004906",
    NOM_IMP: "ERETZ JAVE S DE RL DE CV",
  },
  {
    CVE_IMP: "004362",
    NOM_IMP: "ESPACIOS DINAMICOS WORK SA DE CV",
  },
  {
    CVE_IMP: "004111",
    NOM_IMP: "C LABELING SOLUTIONS SA DE CV",
  },
  {
    CVE_IMP: "004935",
    NOM_IMP: "NMB-MINEBEA DE MEXICO S DE RL DE CV",
  },
  {
    CVE_IMP: "TEM068",
    NOM_IMP: "PRO KIO LOGISTICS S DE RL DE CV / SHOCKWAVE CARGO, LLC",
  },
  {
    CVE_IMP: "004197",
    NOM_IMP: "AGRICULTURA NACIONAL SA DE CV",
  },
  {
    CVE_IMP: "004244",
    NOM_IMP: "PREMIUM TIRES AND WHEELS S.A DE C.V",
  },
  {
    CVE_IMP: "004661",
    NOM_IMP: "ESCOBAS Y TRAPEADORES LA VICTORIA SPR DE RI",
  },
  {
    CVE_IMP: "004750",
    NOM_IMP: "SISTEMAS DE CONTROL NEUMATICO E HIDRAULICO DE MEXICO, SA DE CV",
  },
  {
    CVE_IMP: "004892",
    NOM_IMP: "IMPORTACIONES CAM SA DE CV",
  },
  {
    CVE_IMP: "004212",
    NOM_IMP: "JMM PROYECTOS Y TECNOLOGIA SA DE CV",
  },
  {
    CVE_IMP: "004957",
    NOM_IMP: "INFINITY MAQUINAS SA DE CV",
  },
  {
    CVE_IMP: "TEM099",
    NOM_IMP:
      "EBS EXPERIENCIAS PARA EL ENTRETENIMIENTO SAPI DE CV / EPS AM�RICA, LLC",
  },
  {
    CVE_IMP: "004561",
    NOM_IMP: "PSH PRODUCCIONES S DE RL DE CV",
  },
  {
    CVE_IMP: "004636",
    NOM_IMP: "ZERAUS DE OCCIDENTE SA DE CV",
  },
  {
    CVE_IMP: "TEM105",
    NOM_IMP:
      "PRO KIO LOGISTICS S DE RL DE CV / CIRQUE DU SOLEIL AMERICA NEWCO INC.",
  },
  {
    CVE_IMP: "004624",
    NOM_IMP: "BEFTCOM SA DE CV",
  },
  {
    CVE_IMP: "004944",
    NOM_IMP: "MASSIVE ELECTRONICA HOME SA DE CV",
  },
  {
    CVE_IMP: "TEM094",
    NOM_IMP: "INGENIO DIGITAL Y TELECOMUNICACIONES SA DE CV / SOLOTECH INC",
  },
  {
    CVE_IMP: "004403",
    NOM_IMP: "GRUPO VASKRS SA DE CV",
  },
  {
    CVE_IMP: "004723",
    NOM_IMP: "MIX LIVE PRO ENTERTAINMENT SA DE CV",
  },
  {
    CVE_IMP: "004857",
    NOM_IMP: "NTI CERAMICA SA DE CV",
  },
  {
    CVE_IMP: "999999",
    NOM_IMP: "COTIZACIONES SA DE CV",
  },
  {
    CVE_IMP: "004745",
    NOM_IMP: "MAYDAY DER SA DE CV",
  },
  {
    CVE_IMP: "004742",
    NOM_IMP: "ASSA ABLOY MEXICO SA DE CV",
  },
  {
    CVE_IMP: "004894",
    NOM_IMP: "INGENIO DIGITAL Y TELECOMUNICACIONES SA DE CV",
  },
  {
    CVE_IMP: "004960",
    NOM_IMP: "BASCULAS Y PROYECTOS DE PESAJE SA DE CV",
  },
  {
    CVE_IMP: "004060",
    NOM_IMP: "RC CALIBRACION S.A DE C.V ",
  },
  {
    CVE_IMP: "004718",
    NOM_IMP: "IMPORTACIONES ESPECIALIZADAS AF SA DE CV",
  },
  {
    CVE_IMP: "004917",
    NOM_IMP: "CREACIONES INDUSTRIALES SA DE CV",
  },
  {
    CVE_IMP: "004029",
    NOM_IMP: "GRUPO DE INNOVACION TECNOLOGICA RAM SA DE CV",
  },
  {
    CVE_IMP: "004866",
    NOM_IMP: "MAIN TRADE S DE RL DE CV ",
  },
  {
    CVE_IMP: "004864",
    NOM_IMP: "EBS EXPERIENCIAS PARA EL ENTRETENIMIENTO SAPI DE CV",
  },
];
