import type { Glosa, GlosaError, Validacion, ExpedienteRow, GlosadorLoad } from './types';

export const MOCK_GLOSAS: Glosa[] = [
  {
    id: 'PAE260036',
    ref: 'PAE260036',
    cliente: 'BELCORP PERÚ',
    aduana: 'MEX Pantaco',
    tipo: 'Exportación',
    glosador: 'María G.',
    kam: 'Javier R.',
    status: 'En proceso',
    errores: 3,
    enviada: '2026-04-14 09:12',
    tiempoQA: '1h 24m',
    tiempoKAM: '0m',
    m: 'M1914460',
    monto: 'USD 24,655.24',
  },
  {
    id: 'CIN26E0194',
    ref: 'CIN26E0194',
    cliente: 'KONE MÉXICO',
    aduana: 'Manzanillo',
    tipo: 'Importación',
    glosador: 'María G.',
    kam: 'Javier R.',
    status: 'En espera de cambios',
    errores: 5,
    enviada: '2026-04-13 16:45',
    tiempoQA: '2h 10m',
    tiempoKAM: '6h 32m',
    m: 'M1914133',
    monto: 'USD 138,204.00',
  },
  {
    id: 'PFE260090',
    ref: 'PFE260090',
    cliente: 'BELCORP EL SALVADOR',
    aduana: 'AICM',
    tipo: 'Exportación',
    glosador: 'María G.',
    kam: 'Andrea P.',
    status: 'Nueva',
    errores: 0,
    enviada: '2026-04-15 08:02',
    tiempoQA: '—',
    tiempoKAM: '—',
    m: 'M1914502',
    monto: 'USD 18,900.50',
  },
  {
    id: 'PAE260041',
    ref: 'PAE260041',
    cliente: 'BELCORP COLOMBIA',
    aduana: 'MEX Pantaco',
    tipo: 'Exportación',
    glosador: 'Carlos M.',
    kam: 'Javier R.',
    status: 'Aceptada',
    errores: 1,
    enviada: '2026-04-12 11:30',
    tiempoQA: '3h 02m',
    tiempoKAM: '4h 10m',
    m: 'M1914220',
    monto: 'USD 41,005.00',
  },
  {
    id: 'CIN26E0188',
    ref: 'CIN26E0188',
    cliente: 'KONE MÉXICO',
    aduana: 'AICM',
    tipo: 'Importación',
    glosador: 'Carlos M.',
    kam: 'Andrea P.',
    status: 'En pausa',
    errores: 2,
    enviada: '2026-04-14 14:22',
    tiempoQA: '45m',
    tiempoKAM: '—',
    m: 'M1914301',
    monto: 'USD 9,402.10',
  },
  {
    id: 'PAE260029',
    ref: 'PAE260029',
    cliente: 'BELCORP PERÚ',
    aduana: 'Nuevo Laredo',
    tipo: 'Exportación',
    glosador: 'Carlos M.',
    kam: 'Javier R.',
    status: 'Cerrada',
    errores: 0,
    enviada: '2026-04-10 10:00',
    tiempoQA: '1h 50m',
    tiempoKAM: '2h 15m',
    m: 'M1914012',
    monto: 'USD 55,120.75',
  },
  {
    id: 'PAE260045',
    ref: 'PAE260045',
    cliente: 'NATURA MÉXICO',
    aduana: 'MEX Pantaco',
    tipo: 'Exportación',
    glosador: 'Ana L.',
    kam: 'Rodrigo H.',
    status: 'En proceso',
    errores: 0,
    enviada: '2026-04-15 10:40',
    tiempoQA: '22m',
    tiempoKAM: '—',
    m: 'M1914520',
    monto: 'USD 12,300.00',
  },
  {
    id: 'CIN26E0201',
    ref: 'CIN26E0201',
    cliente: 'SIEMENS MX',
    aduana: 'Veracruz',
    tipo: 'Importación',
    glosador: 'Ana L.',
    kam: 'Rodrigo H.',
    status: 'Nueva',
    errores: 0,
    enviada: '2026-04-15 11:15',
    tiempoQA: '—',
    tiempoKAM: '—',
    m: 'M1914555',
    monto: 'USD 230,450.00',
  },
];

export const MOCK_ERRORES_INITIAL: GlosaError[] = [
  {
    id: 1,
    idx: 1,
    file: 'PAE260036PD.pdf',
    page: 1,
    x: 62,
    y: 18,
    type: 'Dato inexacto',
    category: 'Valor factura vs pedimento',
    note: 'El valor comercial no coincide: pedimento 24,655.24 USD vs factura 24,665.24 USD (diferencia 10 USD).',
    status: 'open',
    createdAt: '09:42',
  },
  {
    id: 2,
    idx: 2,
    file: 'PAE260036PD.pdf',
    page: 1,
    x: 28,
    y: 44,
    type: 'Incongruencia con documento',
    category: 'Incoterm vs factura comercial',
    note: 'En pedimento aparece FCA, en la factura comercial dice FOB.',
    status: 'open',
    createdAt: '09:55',
  },
  {
    id: 3,
    idx: 3,
    file: 'FACT-COM-001.pdf',
    page: 1,
    x: 55,
    y: 70,
    type: 'Documento incorrecto',
    category: 'Otros',
    note: 'La factura comercial no tiene firma del exportador. Anexar versión firmada.',
    status: 'open',
    createdAt: '10:08',
  },
];

export const MOCK_VALIDACIONES: Validacion[] = [
  { field: 'Valor total pedimento vs factura', pedimento: 'USD 24,655.24', factura: 'USD 24,665.24', ok: false, hint: 'Diferencia 10 USD' },
  { field: 'Incoterm pedimento vs factura',     pedimento: 'FCA',            factura: 'FOB',             ok: false, hint: 'No coincide' },
  { field: 'RFC Exportador',                    pedimento: 'TRA950227PX7',   factura: 'TRA950227PX7',    ok: true,  hint: 'Coincide con CASA' },
  { field: 'Fecha de entrada',                  pedimento: '04/03/2026',     factura: '04/03/2026',      ok: true,  hint: 'OK' },
  { field: 'Clave pedimento',                   pedimento: 'A1',             factura: '—',                ok: true,  hint: 'Válida (CAAAREM)' },
  { field: 'Peso bruto total',                  pedimento: '1,693.542 kg',   factura: '1,690.000 kg',    ok: false, hint: 'Diferencia +3.542 kg' },
  { field: 'Fracciones arancelarias',           pedimento: '33030099 (4)',   factura: '33030099 (4)',    ok: true,  hint: 'Todas válidas' },
  { field: 'País origen / destino',             pedimento: 'MEX → SLV',      factura: 'MEX → SLV',       ok: true,  hint: 'OK' },
];

export const MOCK_EXPEDIENTE: ExpedienteRow[] = [
  { key: 'proforma',  label: 'Proforma de pedimento',       required: true,  file: 'PAE260036PD.pdf',       size: '142 KB', uploaded: '14/04/2026 09:01' },
  { key: 'bl',        label: 'Guía Aérea / Bill of Lading', required: true,  file: 'BL-MX2604-008.pdf',     size: '98 KB',  uploaded: '14/04/2026 09:02' },
  { key: 'factura',   label: 'Factura comercial',           required: true,  file: 'FACT-COM-001.pdf',      size: '214 KB', uploaded: '14/04/2026 09:03' },
  { key: 'carta318',  label: 'Carta 3.1.8',                 required: false, file: null,                    size: null,     uploaded: null, hint: 'Sólo importación' },
  { key: 'cove',      label: 'COVE',                        required: true,  file: 'COVE-01702619PS4O2.xml',size: '12 KB',  uploaded: '14/04/2026 09:04' },
  { key: 'm',         label: 'Archivo M (CAAAREM)',         required: true,  file: 'M1914460.txt',          size: '2 KB',   uploaded: '14/04/2026 09:05' },
  { key: 'extras',    label: 'Soporte adicional',           required: false, file: 'packing-list.pdf',      size: '88 KB',  uploaded: '14/04/2026 09:06' },
];

export const MOCK_OP_INFO: Record<string, string> = {
  ref: 'PAE260036',
  pedimento: '6001031',
  patente: '1914',
  tipoOp: 'Exportación (A1)',
  aduana: '370 — AICM',
  cliente: 'TRANSBEL, S.A. DE C.V.',
  clienteRFC: 'TRA950227PX7',
  destinatario: 'BELCORP EL SALVADOR S.A DE C.V',
  paisDestino: 'SLV — El Salvador',
  incoterm: 'FCA',
  moneda: 'USD',
  valorComercial: '24,655.24',
  fechaEntrada: '04/03/2026',
  pesoBruto: '1,693.542 kg',
  bultos: '7',
  m: 'M1914460',
  glosador: 'María G.',
  kam: 'Javier R.',
};

export const MOCK_FILES: { key: string; name: string; label: string }[] = [
  { key: 'pedimento', name: 'PAE260036PD.pdf',    label: 'Pedimento' },
  { key: 'factura',   name: 'FACT-COM-001.pdf',   label: 'Factura' },
  { key: 'bl',        name: 'BL-MX2604-008.pdf',  label: 'BL' },
  { key: 'cove',      name: 'COVE-01702619PS4O2', label: 'COVE' },
  { key: 'm',         name: 'M1914460.txt',       label: 'Archivo M' },
];

export const MOCK_GLOSADORES: GlosadorLoad[] = [
  { name: 'María G.',  init: 'M', bg: '#8B5CF6', capacity: 5, inProgress: 3, waiting: 1, avgTime: '1h 45m', errors30d: 18 },
  { name: 'Carlos M.', init: 'C', bg: '#3B82F6', capacity: 5, inProgress: 2, waiting: 1, avgTime: '2h 10m', errors30d: 22 },
  { name: 'Ana L.',    init: 'A', bg: '#EAB308', capacity: 5, inProgress: 2, waiting: 0, avgTime: '1h 30m', errors30d: 14 },
  { name: 'Diego V.',  init: 'D', bg: '#22C55E', capacity: 5, inProgress: 0, waiting: 0, avgTime: '—',      errors30d: 0, status: 'Vacaciones' },
];
