import {
  USER_CASA_USERNAME_VALIDATION,
  USER_EMAIL_VALIDATION,
  USER_MOBILE_VALIDATION,
  USER_NAME_VALIDATION,
  USER_OPTIONAL_PASSWORD_VALIDATION,
  USER_ROLE_ID_VALIDATION,
  USER_STATUS_VALIDATION,
} from "@/lib/validations/userValidations";
import { z } from "zod/v4";

export const modifyUserSchema = z.object({
  name: USER_NAME_VALIDATION,
  email: USER_EMAIL_VALIDATION,
  mobile: USER_MOBILE_VALIDATION,
  password: USER_OPTIONAL_PASSWORD_VALIDATION,
  role_id: USER_ROLE_ID_VALIDATION,
  casa_user_name: USER_CASA_USERNAME_VALIDATION,
  status: USER_STATUS_VALIDATION,
});
