export type ExceptionJson = Record<string, Record<string, string[]>>;

export const exceptionCodes = {
  "AGENTE DE ADUANA": {
      "DEMORAS EN PROCESO ADUANERO": [
        "AA01 DEMORA EN LA SOLICITUD EN EL PAGO DE IMPUESTOS",
        "AA02 DEMORA POR ERROR U OMISION",
        "AA03 DEMORA POR PERDIDA O CONFUSION DE DOCUMENTOS",
        "AA04 ERROR O RETRASO CERTIFICADO DE ORIGEN",
        "AA05 DEMORA EN LA RADICACION DE LOS DOCUMENTOS ADUANALES",
        "AA07 OMITE EL PROCESO ADUANERO A TIEMPO, POR FALTA DE INFORMACION"
      ],
      "REQUISITOS ADICIONALES": [
        "AA06 DEMORA EN LA SOLICITUD DE REQUISITOS ADICIONALES"
      ]
    },
    "AGLOG 4PL": {
    "CAMBIO DE FECHA DE PICK UP": [
      "AL07 RECOGIDA DE LA CARGA ANTES O DESPUES DE LA FECHA CONFIRMADA POR EL PROVEEDOR"
    ],
    "DEMORA EN CREACION DE EE": [
      "AL04 SOLICITUD  TARDIA EN LA EE (SCC)",
      "AL05 CREACION TARDIA DE LA EE (COORDINADOR EE)"
    ],
    "DEMORA EN EL SUMINISTRO DE TARIFAS": [
      "AL02 DEMORA EN LA COTIZACIàN DE TARIFAS"
    ],
    "DEMORA, CAMBIO O  INSTRUCCIàN ERRADA": [
      "AL01 DETALLES DE RESERVA NO AJUSTABLES A LOS TIEMPOS O RUTA DEL RATE CARD",
      "AL03 DEMORA O ERROR EN EL SUMINISTRO DE INSTRUCCIàN"
    ],
    "LLEGADA DE LA MERCANCIA POR FUERA DEL RANGO DE LA FECHA COMPROMISO DE ENTREGA A CDP": [
      "AL06 LLEGADA DE LA MERCANCIA ANTES DE LA FECHA COMPROMISO DE ENTREGA EN CDP"
    ]
  },
  "BELCORP": {
    "CAMBIO EN EL ENVIO DE DOCUMENTOS COMERCIALES": [
      "BC13 GRUPO FACTURADO ANTES O DESPUES DE LA FECHA INFORMADA EN LA INSTRUCCIàN"
    ],
    "CAMBIO Y/O DEMORA EN EL PICK UP DATE O SHIPMENT RECEIVED": [
      "BC23 LA CARGA NO ESTA LISTA Y/O ESTA EN MAL ESTADO"
    ],
    "DEMORA EN CREACION DE EE": [
      "BC18 DEMORA EN LA ACTUALIZACION DE CANTIDADES",
      "BC19 DEMORA EN LA ACTUALIZACION DE PRECIOS",
      "BC20 DEMORA EN LA ACTUALIZACION DE CANTIDADES Y PRECIOS",
      "BC21 INFORMACION INCOMPLETA EN SAP",
      "BC22 CAMBIO DE PO LINES"
    ],
    "DEMORA EN EL SUMINISTRO DE TARIFAS": [
      "BC01 DEMORA EN APROBACION DE TARIFAS"
    ],
    "DEMORA, CAMBIO O  INSTRUCCIàN ERRADA": [
      "BC10 CAMBIO DE INSTRUCCION (FCL, LCL, AEREO, TERRESTRE, COURIER, MCC)",
      "BC11 DEMORA EN EL SUMINISTRO DE INFORMACION",
      "BC12 INSTRUCCIàN ERRADA"
    ],
    "DOCUMENTOS ORIGINALES CON INFORMACION ERRADA": [
      "BC06 FACTURAS / LISTA DE EMPAQUE",
      "BC07 CERTIFICADO DE ORIGEN",
      "BC08 CARTAS DE RESPONSABILIDAD/NO APERTURA",
      "BC09 OTROS DOCUMENTOS",
      "BC27 OTROS DOCUMENTOS (CERTIFICADO DE CARGA PELIGROSA, CARTAS DE RESPONSABILIDAD, SLI, ETC)"
    ],
    "FERIADO EN CUALQUIER PROCESO DE LOGISTICA": [
      "BC28 FERIADO O DIA NO LABORAL EN PAIS"
    ],
    "LLEGADA DE LA MERCANCIA POR FUERA DEL RANGO DE LA FECHA COMPROMISO DE ENTREGA A CDP": [
      "BC24 CAMBIO DE FECHA REQUERIDA POSTERIOR AL ACUERDO INICIAL "
    ],
    "NO RECEPCION Y/O DEMORA EN LA RECEPCION DE LA CARGA EN EL CPAC/CDP": [
      "BC14 FALTA DE DISPONIBILIDAD DE ESPACIO EN CPAC/CDP",
      "BC15 PRIORIZACION EN ADUANA O ENTREGA POR PARTE DE BELCORP"
    ],
    "OTRAS DEMORAS": [
      "BC16 DEMORA EN EL PAGO DE IMPUESTOS",
      "BC17 EXCESO DE CAPACITY SOBRE EL NEGOCIADO"
    ],
    "PROBLEMAS CON LA MERCANCÖA": [
      "BC29 CARGA MAL ETIQUETADA"
    ],
    "RETRASO CONEXOS A LA OPERACIàN": [
      "BC02 DEMORAS POR CONSOLIDACION/DESCONSOLIDACION DE CARGA"
    ],
    "RETRASO EN EL ENVIO DE DOCUMENTOS ORIGINALES": [
      "BC03 FACTURAS / LISTA DE EMPAQUE",
      "BC04 CARTAS DE RESPONSABILIDAD/NO APERTURA",
      "BC05 OTROS DOCUMENTOS",
      "BC25 CERTIFICADO DE ORIGEN",
      "BC26 OTROS DOCUMENTOS (CERTIFICADO DE CARGA PELIGROSA, CARTAS DE RESPONSABILIDAD, SLI, ETC)"
    ]
  },
  "FACTORES EXTERNOS": {
    "CONGESTION PORTUARIA PARA TRANSPORTADORES": [
      "FE23 DEMORA EN LA ASIGNACION DE CITAS PARA CARGUE"
    ],
    "DEMORA EN APROBACION DE VISTOS BUENOS": [
      "FE12 DEMORA POR INEN",
      "FE13 DEMORA POR INVIMA",
      "FE14 DEMORA POR ANVISA",
      "FE15 DEMORA POR REGISTRO DE IMPORTACION",
      "FE16 DEMORA POR OTROS VISTOS BUENOS",
      "FE17 DEMORA POR AGEMED"
    ],
    "DEMORA EN CREACION DE EE": [
      "FE30 FALLAS EN EL SISTEMA"
    ],
    "DEMORAS EN CONEXIàN": [
      "FE26 RETRASO POR CONGESTION EN PUERTOS DE CONEXIàN ANTERIORES"
    ],
    "DEMORAS EN PROCESOS GUBERNAMENTALES (INSPECCION FISICA, INSPECCION POR PERFILAMIENTO, BOLETIN QUIMICO, ETC)": [
      "FE03 CANAL ROJO (INSPECCION FISICA)",
      "FE04 BOLETIN QUIMICO",
      "FE05 PERFILAMIENTO (INSPECCION DISTINTA A LA ENTIDAD ADUANAL)",
      "FE06 FALLA EN EL SISTEMA DE LA ENTIDAD ADUANAL",
      "FE07 CAMBIOS EN LEYES GUBERNAMENTALES",
      "FE08 SOLICITUD REQUERIMIENTOS ADICIONALES"
    ],
    "FACTORES  QUE IMPIDEN à DEMORAN EL TRANSITO DEL EMBARQUE": [
      "FE18 FACTORES CLIMATICOS",
      "FE19 FALLAS MECANICAS Y/O ACCIDENTE EN LOS MEDIOS DE TRANSPORTE",
      "FE20 HUELGAS, ASONADAS, PAROS à BLOQUEOS (RESTRICCION VEHICULAR)",
      "FE21 CONGESTION EN PUERTO à AEROPUERTO",
      "FE22 RESTRICCION DE LA AEROLINEA O LINEA NAVIERA PARA EL EMBARQUE DE LA M/CIA POR COMPATIBILIDAD DE IMOS",
      "FE25 FECHA DE COMPROMISO DEL PROVEEDOR VS FECHA DE CUT OFF REAL",
      "FE29 IMPOSIBILIDAD PARA EL CARGUE EL MISMO DIA POR RESTRICCION DEL DEPOSITO/PUERTO"
    ],
    "FERIADO EN CUALQUIER PROCESO DE LOGISTICA": [
      "FE24 FERIADO O DIA NO LABORAL EN PAIS"
    ],
    "INSPECCION EN CONEXIàN": [
      "FE27 RETRASO POR INSPECCION EN PUERTOS DE CONEXIàN ANTERIORES"
    ],
    "NO RECALADA DE LA MOTONAVE": [
      "FE09 NO RECALADA POR INCUMPLIMIENTO DE ITINERARIOS",
      "FE10 AVERIA GRUESA"
    ],
    "OTRAS DEMORAS": [
      "FE02 EXCESO DE CAPACITY SOBRE EL NEGOCIADO"
    ],
    "RESTRICCION DEL MERCADO": [
      "FE28 REDUCCION DE ESPACIO POR COYUNYURA DEL MERCADO"
    ],
    "RETRASO CONEXOS A LA OPERACIàN": [
      "FE01 DEMORAS POR CONSOLIDACION/DESCONSOLIDACION DE CARGA"
    ],
    "RETRASO DEL MEDIO DE TRANSPORTE": [
      "FE11 DEMORAS POR PESO Y BALANCE"
    ]
  },
  "FFW 3PL": {
    "CAMBIO DE FECHA DE PICK UP": [
      "FF23 RECOGIDA DE LA CARGA ANTES O DESPUES DE LA FECHA CONFIRMADA POR EL PROVEEDOR"
    ],
    "CAPACIDAD DE LA CONEXIàN": [
      "FF25 CAPACIDAD DE LA CONEXIàN MENOR A LA DEL PRIMER TRAMO"
    ],
    "DEMORA EN EL SUMINISTRO DE TARIFAS": [
      "FF21 DEMORA EN CONFIRMACION DE TARIFAS"
    ],
    "DEMORA, CAMBIO O  INSTRUCCIàN ERRADA": [
      "FF13 REDUCCION DE CAPACITY",
      "FF14 DEMORA EN EL SUMINISTRO DE INFORMACION",
      "FF15 INSTRUCCIàN ERRADA",
      "FF16 DEMORAS POR ENVIO DE CARGA PARCIALIZADA",
      "FF17 ERROR U OMISION POR PARTE DEL MEDIO TRANSPORTE",
      "FF20 DETALLES DE RESERVA NO AJUSTABLES A LOS TIEMPOS O RUTA DEL RATE CARD"
    ],
    "DISPONIBILIDAD DE VEHICULOS": [
      "FF24 DEMORA EN LA ASIGNACION DE VEHICULOS"
    ],
    "DOCUMENTOS ORIGINALES CON INFORMACION ERRADA": [
      "FF09 FACTURAS Y/O CERTIFICACION DE FLETES",
      "FF10 CERTIFICACION DE TRANSBORDO",
      "FF11 DOCUMENTO DE TRANSPORTE",
      "FF12 OTROS DOCUMENTOS"
    ],
    "LLEGADA DE LA MERCANCIA POR FUERA DEL RANGO DE LA FECHA COMPROMISO DE ENTREGA A CDP": [
      "FF22 LLEGADA DE LA MERCANCIA ANTES DE LA FECHA COMPROMISO DE ENTREGA EN CDP"
    ],
    "PROBLEMAS CON LA MERCANCIA": [
      "FF01 DA¥OS, AVERIAS, ABOLLADURAS O GOLPES DE LA CARGA",
      "FF02 PERDIDA PARCIAL O TOTAL DE LA MERCANCIA (ROBO)"
    ],
    "RETRASO DEL MEDIO DE TRANSPORTE": [
      "FF18 REDUCCION DE CAPACITY //FALTA O RESTRICCION DE ESPACIOS (BACKLOG)",
      "FF19 DEMORAS POR CONSOLIDACION/DESCONSOLIDACION DE CARGA"
    ],
    "RETRASO EN EL ENVIO DE DOCUMENTOS ORIGINALES": [
      "FF03 FACTURAS / LISTA DE EMPAQUE",
      "FF04 CERTIFICADO DE ORIGEN",
      "FF05 FACTURAS Y/O CERTIFICACION DE FLETES",
      "FF06 CERTIFICACION DE TRANSBORDO",
      "FF07 DOCUMENTO DE TRANSPORTE",
      "FF08 OTROS DOCUMENTOS"
    ]
  },
  "OTRO 3PL": {
    "DEMORA, CAMBIO O  INSTRUCCIàN ERRADA": [
      "OL10 DEMORA EN EL SUMINISTRO DE INFORMACION",
      "OL11 INSTRUCCIàN ERRADA",
      "OL12 ERROR U OMISION POR PARTE DEL MEDIO TRANSPORTE",
      "OL15 DETALLES DE RESERVA NO AJUSTABLES A LOS TIEMPOS O RUTA DEL RATE CARD"
    ],
    "DISPONIBILIDAD DE VEHICULOS": [
      "OL14 DEMORA EN LA ASIGNACION DE VEHICULOS"
    ],
    "DOCUMENTOS ORIGINALES CON INFORMACION ERRADA": [
      "OL07 FACTURAS Y/O CERTIFICACION DE FLETES",
      "OL08 DOCUMENTO DE TRANSPORTE",
      "OL09 OTROS DOCUMENTOS"
    ],
    "PROBLEMAS CON LA MERCANCIA": [
      "OL01 DA¥OS, AVERIAS, ABOLLADURAS O GOLPES DE LA CARGA",
      "OL02 PERDIDA PARCIAL O TOTAL DE LA MERCANCIA (ROBO)"
    ],
    "RETRASO DEL MEDIO DE TRANSPORTE": [
      "OL13 DEMORAS POR CONSOLIDACION/DESCONSOLIDACION DE CARGA"
    ],
    "RETRASO EN EL ENVIO DE DOCUMENTOS ORIGINALES": [
      "OL03 OTROS DOCUMENTOS",
      "OL04 FACTURAS / LISTA DE EMPAQUE",
      "OL05 FACTURAS Y/O CERTIFICACION DE FLETES",
      "OL06 DOCUMENTO DE TRANSPORTE"
    ]
  },
  "PROVEEDOR": {
    "CAMBIO Y/O DEMORA EN EL PICK UP DATE O SHIPMENT RECEIVED": [
      "PR12 ENTREGA DE LA CARGA DESPUES DEL CUT OFF",
      "PR13 ENTREGA DE LA CARGA ANTES DEL CUT OFF"
    ],
    "DEMORA EN CREACION DE EE": [
      "PR01 DEMORA EN LA ACTUALIZACION DE CANTIDADES Y PRECIOS"
    ],
    "DEMORA, CAMBIO O  INSTRUCCIàN ERRADA": [
      "PR10 DEMORA EN EL SUMINISTRO DE INFORMACION",
      "PR11 INSTRUCCIàN ERRADA"
    ],
    "DEMORAS EN LA ENTREGA DE MERCANCIA": [
      "PR14 EL PROVEEDOR ENTREGA LA MERCANCIA DESPUES DE LA FECHA DE COMPROMISO",
      "PR15 EL PROVEEDOR ENTREGA LA MERCANCIA ANTES DE LA FECHA DE COMPROMISO"
    ],
    "DEMORAS EN LA LIBERACION DE DOCUMENTOS": [
      "PR16 DEMORA DE PAGOS EN ORIGEN"
    ],
    "DOCUMENTOS ORIGINALES CON INFORMACION ERRADA": [
      "PR07 FACTURAS COMERCIALES / LISTA DE EMPAQUE (CANTIDADES, PRECIOS, CONSECUTIVO, ETC)",
      "PR08 CERTIFICADO DE ORIGEN",
      "PR09 OTROS DOCUMENTOS (CERTIFICADO DE CARGA PELIGROSA, CARTAS DE RESPONSABILIDAD, SLI, ETC)"
    ],
    "PROBLEMAS CON LA MERCANCIA": [
      "PR02 EMBALAJE NO APROPIADO",
      "PR03  CARGA MAL ETIQUETADA "
    ],
    "RETRASO EN EL ENVIO DE DOCUMENTOS ORIGINALES": [
      "PR04 FACTURAS COMERCIALES / LISTA DE EMPAQUE",
      "PR05 CERTIFICADO DE ORIGEN",
      "PR06 OTROS DOCUMENTOS (CERTIFICADO DE CARGA PELIGROSA, CARTAS DE RESPONSABILIDAD, SLI, ETC)"
    ]
  },
  "TRANSPORTADOR": {
    "CAMBIO DE FECHA DE PICK UP": [
      "TL01 RECOGIDA DE LA CARGA ANTES O DESPUES DE LA FECHA CONFIRMADA POR EL BELCORP"
    ],
    "CONDICIONES DE VEHICULO": [
      "TL04 VEHICULOS QUE NO CUMPLEN CON LOS REQUISITOS DE BELCORP"
    ],
    "DEMORA, CAMBIO O  INSTRUCCION ERRADA": [
      "TL05 DEMORA EN EL SUMINISTRO DE INFORMACION"
    ],
    "DEMORA, CAMBIO O  INSTRUCCIàN ERRADA": [
      "TL06 TIEMPO DE TRANSITO MAYOR A LO OFERTADO"
    ],
    "DISPONIBILIDAD DE VEHICULOS": [
      "TL02 DEMORA EN LA ASIGNACION DE VEHICULOS EN ORIGEN",
      "TL03 DEMORA EN LA ASIGNACION DE VEHICULOS EN DESTINO"
    ],
    "DOCUMENTOS ORIGINALES CON INFORMACION ERRADA": [
      "TL08 DOCUMENTO DE TRANSPORTE",
      "TL09 OTROS DOCUMENTOS"
    ],
    "RETRASO EN EL ENVIO DE DOCUMENTOS ORIGINALES": [
      "TL07 DOCUMENTO DE TRANSPORTE",
      "TL10 DOCUMENTO DE TRANSPORTE"
    ]
  }
};
